# Just the Docs Settings
theme: bulma-clean-theme

# This enables the "Table of Contents" on the right for long research posts
toc:
  enabled: true
  max_level: 3

# This allows you to add a custom "Call to Action" or Bio at the bottom of the left nav
side_bar:
  custom_content: |
    <hr>
    <p><strong>Tommy T. Douglas</strong></p>
    <p><small>Independent Researcher & Heart Attack Survivor (2008)</small></p>
color_scheme: medical
search_enabled: true
heading_anchors: true
